[server]
maxUploadSize = 10000  # <--- Changed from 5000 to 10000 to support your 8GB files
# enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#6366f1"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
font = "sans serif"
